# -*- coding: utf-8 -*-
"""dosage_model_hybrid_optimized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sez9806a_TpH1tjDhYPf59m9o1iQjdoz

# Dosage Model - Optimized Hybrid Notebook

This notebook improves the earlier version in two important ways:

1. It keeps route labels aligned with the dataset and test file (`PO`, `IV`, `IM`) instead of converting `PO` to `oral`.
2. It uses a **hybrid predictor**:
   - first, exact lookup from the cleaned training table
   - then a machine learning fallback for unseen combinations

That gives much better performance on the prepared manual test cases.
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import joblib

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Set your dataset path here
DATA_PATH = '/content/drive/MyDrive/d_dose.csv'
TEST_CASES_PATH = '/content/drive/MyDrive/manual_test_cases_unambiguous.csv'

# Output files
DOSE_MODEL_PATH = '/content/drive/MyDrive/dose_model_hybrid.pkl'
ROUTE_MODEL_PATH = '/content/drive/MyDrive/route_model_hybrid.pkl'
LOOKUP_TABLE_PATH = '/content/drive/MyDrive/dose_route_lookup.csv'


df_raw = pd.read_csv(DATA_PATH)
print('Raw shape:', df_raw.shape)
df_raw.head()

# =========================
# Selected overlap antibiotics only
# =========================
SELECTED_ANTIBIOTICS = [
    'amikacin', 'ampicillin', 'aztreonam', 'cefazolin', 'cefepime',
    'cefotaxime', 'cefoxitin', 'cefpodoxime', 'ceftazidime', 'ceftriaxone',
    'cefuroxime', 'chloramphenicol', 'ciprofloxacin', 'clarithromycin',
    'clindamycin', 'doripenem', 'doxycycline', 'ertapenem', 'erythromycin',
    'fosfomycin', 'gentamicin', 'levofloxacin', 'linezolid', 'meropenem',
    'metronidazole', 'moxifloxacin', 'nitrofurantoin', 'streptomycin',
    'tetracycline', 'tigecycline', 'tobramycin', 'vancomycin'
]

def normalize_ab_name(x):
    if pd.isna(x):
        return np.nan
    return str(x).strip().lower()

# Preserve original for display if needed
df_raw['generic_original'] = df_raw['generic']

# Normalize generic names
df_raw['generic'] = df_raw['generic'].apply(normalize_ab_name)

# Filter to selected antibiotics only
df_raw = df_raw[df_raw['generic'].isin(SELECTED_ANTIBIOTICS)].copy()

print("Filtered raw shape (selected antibiotics only):", df_raw.shape)
print("Unique selected antibiotics found in dosage dataset:", df_raw['generic'].nunique())
print("Antibiotics present:", sorted(df_raw['generic'].dropna().unique().tolist()))

missing_in_dosage = sorted(set(SELECTED_ANTIBIOTICS) - set(df_raw['generic'].dropna().unique()))
print("Missing from dosage dataset:", missing_in_dosage)

# Keep only needed columns
keep_cols = [
    'generic', 'disease',
    'min_age_d', 'max_age_d',
    'min_age_m', 'max_age_m',
    'min_age_y', 'max_age_y',
    'min_dose_dw_mg', 'max_dose_dw_mg',
    'min_dose_dw_iu', 'max_dose_dw_iu',
    'route'
]

df = df_raw[keep_cols].copy()
df = df.dropna(subset=['generic', 'disease', 'route']).copy()

# Safety: ensure generic stays normalized
df['generic'] = df['generic'].apply(normalize_ab_name)

# Optional: standardize disease text a little
df['disease'] = df['disease'].astype(str).str.strip()

print("Working rows after keep/dropna:", df.shape)
print("Working antibiotics:", sorted(df['generic'].unique().tolist()))

# IMPORTANT: keep route labels aligned with your test set
# The test file expects PO, IV, IM
route_map = {
    'PO': 'PO',
    'IV': 'IV',
    'IM': 'IM'
}
df['route'] = df['route'].astype(str).str.strip().map(route_map).fillna(df['route'].astype(str).str.strip())


def build_dose_range(row):
    if pd.notna(row['min_dose_dw_mg']) and pd.notna(row['max_dose_dw_mg']):
        return f"{int(row['min_dose_dw_mg'])}-{int(row['max_dose_dw_mg'])} mg"
    if pd.notna(row['min_dose_dw_iu']) and pd.notna(row['max_dose_dw_iu']):
        return f"{int(row['min_dose_dw_iu'])}-{int(row['max_dose_dw_iu'])} units"
    return 'unknown'


def age_group_from_ranges(row):
    year_vals = [v for v in [row['min_age_y'], row['max_age_y']] if pd.notna(v)]
    if year_vals:
        avg_age = sum(year_vals) / len(year_vals)
        if avg_age < 12:
            return 'child'
        elif avg_age < 65:
            return 'adult'
        else:
            return 'elderly'

    # Any day/month-only record is treated as child
    if any(pd.notna(v) for v in [row['min_age_d'], row['max_age_d'], row['min_age_m'], row['max_age_m']]):
        return 'child'

    return 'adult'


df['dose_range'] = df.apply(build_dose_range, axis=1)
df['age_group'] = df.apply(age_group_from_ranges, axis=1)

df[['generic', 'disease', 'age_group', 'dose_range', 'route']].head()

# Inspect ambiguity in the original dataset
input_cols = ['generic', 'disease', 'age_group']

route_counts = (
    df.groupby(input_cols + ['route'])
      .size()
      .reset_index(name='count')
)

dose_counts = (
    df.groupby(input_cols + ['dose_range'])
      .size()
      .reset_index(name='count')
)

route_ambiguity = route_counts.groupby(input_cols)['route'].nunique().reset_index(name='num_routes')
dose_ambiguity = dose_counts.groupby(input_cols)['dose_range'].nunique().reset_index(name='num_dose_ranges')

print('Unique input combinations:', len(route_ambiguity))
print('Inputs with multiple possible routes:', (route_ambiguity['num_routes'] > 1).sum())
print('Inputs with multiple possible dose ranges:', (dose_ambiguity['num_dose_ranges'] > 1).sum())

# Collapse each input to the most frequent dose and most frequent route
# This gives one stable answer per (generic, disease, age_group)
lookup_df = (
    df.groupby(input_cols)
      .agg(
          dose_range=('dose_range', lambda s: s.value_counts().idxmax()),
          route=('route', lambda s: s.value_counts().idxmax()),
          support=('route', 'size')
      )
      .reset_index()
)

lookup_df.to_csv(LOOKUP_TABLE_PATH, index=False)
print('Lookup table rows:', len(lookup_df))
lookup_df.head()

# Train fallback ML models for unseen combinations
feature_cols = ['generic', 'disease', 'age_group']
X = lookup_df[feature_cols].copy()
y_dose = lookup_df['dose_range'].copy()
y_route = lookup_df['route'].copy()

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), feature_cols)
    ]
)

dose_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        n_estimators=500,
        random_state=42,
        class_weight='balanced_subsample'
    ))
])

route_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        n_estimators=500,
        random_state=42,
        class_weight='balanced_subsample'
    ))
])

print("Training rows:", len(X))
print("Unique antibiotics in lookup_df:", lookup_df['generic'].nunique())
print("Antibiotics in training set:", sorted(lookup_df['generic'].unique().tolist()))

if len(X) == 0:
    raise ValueError("No training rows left after filtering to selected antibiotics.")

if lookup_df['generic'].nunique() == 0:
    raise ValueError("No selected antibiotics found in lookup table.")

dose_model.fit(X, y_dose)
route_model.fit(X, y_route)

joblib.dump(dose_model, DOSE_MODEL_PATH)
joblib.dump(route_model, ROUTE_MODEL_PATH)

print('Saved dose model to:', DOSE_MODEL_PATH)
print('Saved route model to:', ROUTE_MODEL_PATH)

# Exact-lookup dictionaries used before ML fallback
exact_dose_lookup = {
    (row['generic'], row['disease'], row['age_group']): row['dose_range']
    for _, row in lookup_df.iterrows()
}

exact_route_lookup = {
    (row['generic'], row['disease'], row['age_group']): row['route']
    for _, row in lookup_df.iterrows()
}


def age_group(age):
    if age < 12:
        return 'child'
    elif age < 65:
        return 'adult'
    else:
        return 'elderly'


def validate_sample(sample):
    generic_norm = normalize_ab_name(sample['generic'])
    if generic_norm not in SELECTED_ANTIBIOTICS:
        raise ValueError(f"Antibiotic '{sample['generic']}' is not in the selected 32 antibiotics.")
    return generic_norm

def predict_dose_and_route(sample, dose_model, route_model, exact_dose_lookup, exact_route_lookup):
    generic_norm = validate_sample(sample)
    ag = age_group(sample['age'])
    key = (generic_norm, sample['disease'], ag)

    input_df = pd.DataFrame([{
        'generic': generic_norm,
        'disease': sample['disease'],
        'age_group': ag
    }])

    # First try exact match from cleaned lookup table
    if key in exact_dose_lookup:
        pred_dose = exact_dose_lookup[key]
        dose_source = 'lookup'
    else:
        pred_dose = dose_model.predict(input_df)[0]
        dose_source = 'model'

    if key in exact_route_lookup:
        pred_route = exact_route_lookup[key]
        route_source = 'lookup'
    else:
        pred_route = route_model.predict(input_df)[0]
        route_source = 'model'

    return {
        'generic': sample['generic'],
        'disease': sample['disease'],
        'age': sample['age'],
        'age_group': ag,
        'predicted_dose': pred_dose,
        'predicted_route': pred_route,
        'dose_source': dose_source,
        'route_source': route_source
    }

# Single test case
sample = {
    'generic': 'amikacin',   # keep lowercase to match training filter
    'disease': 'Bacteremia',
    'age': 70
}

result = predict_dose_and_route(sample, dose_model, route_model, exact_dose_lookup, exact_route_lookup)
print('Predicted Dose:', result['predicted_dose'])
print('Predicted Route:', result['predicted_route'])
print('Dose Source:', result['dose_source'])
print('Route Source:', result['route_source'])

# Batch test against the clean unambiguous manual test set
# This is the block you can run to evaluate everything at once.

test_df = pd.read_csv(TEST_CASES_PATH)

# Normalize and filter test set to the same 32 antibiotics
test_df['generic'] = test_df['generic'].apply(normalize_ab_name)
test_df = test_df[test_df['generic'].isin(SELECTED_ANTIBIOTICS)].copy()

print("Filtered test cases shape:", test_df.shape)
print("Test antibiotics present:", sorted(test_df['generic'].unique().tolist()))
results = []

for _, row in test_df.iterrows():
    sample = {
        'generic': row['generic'],
        'disease': row['disease'],
        'age': int(row['sample_age'])
    }

    pred = predict_dose_and_route(sample, dose_model, route_model, exact_dose_lookup, exact_route_lookup)

    expected_dose = row['expected_dose_range']
    expected_route = row['expected_route']

    dose_match = pred['predicted_dose'] == expected_dose
    route_match = pred['predicted_route'] == expected_route

    results.append({
        'generic': sample['generic'],
        'disease': sample['disease'],
        'age': sample['age'],
        'age_group': pred['age_group'],
        'expected_dose': expected_dose,
        'predicted_dose': pred['predicted_dose'],
        'dose_match': dose_match,
        'expected_route': expected_route,
        'predicted_route': pred['predicted_route'],
        'route_match': route_match,
        'both_match': dose_match and route_match,
        'dose_source': pred['dose_source'],
        'route_source': pred['route_source']
    })

results_df = pd.DataFrame(results)

print('Total Test Cases:', len(results_df))
print('Dose Correct:', results_df['dose_match'].sum())
print('Route Correct:', results_df['route_match'].sum())
print('Both Correct:', results_df['both_match'].sum())
print('Dose Accuracy: {:.2f}%'.format(results_df['dose_match'].mean() * 100))
print('Route Accuracy: {:.2f}%'.format(results_df['route_match'].mean() * 100))
print('Overall Accuracy (Both): {:.2f}%'.format(results_df['both_match'].mean() * 100))

results_df.head()

# Optional: inspect wrong predictions only
wrong_df = results_df[results_df['both_match'] == False].copy()
print('Wrong rows:', len(wrong_df))
wrong_df